server:
  port: 0

spring:
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER:http://localhost:8090/}
  jackson:
   serialization:
     FAIL_ON_EMPTY_BEANS: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8061/eureka/}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        
